# Assignment - 6.0 {Numpy}

## Theoretical Questions:

Q 1. Explain the purpose and advantages of numpy and scientific computing and data analysis how does it enhance pythons capabilities for numerical operations .

🔶 Purpose of NumPy

NumPy (Numerical Python) is a foundational package for scientific computing in Python. It enhances Python’s capabilities by introducing support for multi-dimensional arrays, efficient numerical computations, and a wide array of mathematical functions. Its primary role in scientific computing and data analysis is to provide an efficient way to perform operations on large datasets .

 1 .Efficient Array Operations: NumPy provides the ndarray object, a powerful data structure that supports multi-dimensional arrays (e.g., matrices, tensors) and allows for element-wise operations. This is a significant improvement over Python’s built-in lists, which are not optimized for numerical tasks.

2 .Mathematical and Statistical Functions: NumPy offers a comprehensive library of functions for mathematical operations such as linear algebra ,matrix multiplication, and statistical calculations.

3 . Interoperability: NumPy serves as the core data structure for many other Python libraries like Pandas, SciPy, and Scikit-learn, making it a crucial building block for data analysis, machine learning, and scientific computing ecosystems.

🔶 Advantages of NumPy 

1. Performance Optimization: NumPy is implemented in C and Fortran, which are much faster than pure Python.

2. Memory Efficiency: NumPy arrays are more memory-efficient than Python lists, especially when dealing with large datasets. A Python list contains pointers to data, while NumPy arrays store data directly in contiguous memory blocks, reducing overhead.

3. Multi-Dimensional Arrays Support: NumPy provides native support for multi-dimensional arrays, which are essential for numerical computing and scientific problems that often require 2D (matrices), 3D, or higher-dimensional arrays.

4. Ease of Complex Mathematical Operations: NumPy simplifies complex operations like matrix multiplications, eigenvalue computations, solving systems of equations, and other.

5. Data Compatibility and Integration: NumPy arrays can easily be integrated with libraries like Pandas .

   

In [2]:
#capabilities for numerical operations

#( 1 )creating array
import numpy as np

# 1D 
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

# 2D 
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

# 3D 
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# (2)operation
a = np.array([41 , 12 , 35 , 48])
b = np.array([5 , 6 , 7 , 8])

#addition
addition = a + b
print("Addition:", addition)

#  multiplication
multiplication = a * b
print("Multiplication:", multiplication)

#  division
division = a  / b
print("Division:", division)

Addition: [46 18 42 56]
Multiplication: [205  72 245 384]
Division: [8.2 2.  5.  6. ]


Q 2. Compare and contrast np.mean and np.average functions and numpy when would you use one over the other ?

Comparision b/w np.mean and no.average

 .Basic Functionality

🟣 np.mean():

Purpose: Computes the arithmetic mean (average) of elements in an array.

Default behavior: Computes the mean across all elements of the array. If you specify an axis, it computes the mean along that axis.

Weighting: Does not support weighted averages; every element is treated equally.

 

In [7]:
#use of np.mean
import numpy as np

data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)
print(mean_value) 

matrix = np.array([[1, 2], [3, 4], [5, 6]])
mean_by_row = np.mean(matrix, axis=1)
print(mean_by_row) 

3.0
[1.5 3.5 5.5]


🟣 np.average():

Purpose: Computes the weighted average of elements in an array. It can also compute the arithmetic mean when no weights are provided.

Default behavior: Computes the arithmetic mean if no weights are specified. If weights are provided, computes the weighted average.

Weighting: Supports weighted averages through the weights parameter, allowing you to assign different importances to different elements.


In [8]:
# use of np.average()
import numpy as np

data = np.array([41 , 12 , 35 , 48])
weights = np.array([5 , 6 , 7 , 8])

before_avg__ = np.average( data , weights = weights)
print(before_avg__)

after_avg__ = np.average( data )
print(after_avg__)


34.84615384615385
34.0


Q 3. Describe the methods for reversing a numpy array along different Axis provide examples for 1D and 2D arrays ?

Reversing a NumPy array means flipping the elements in the array, and this can be done along different axes for multi-dimensional arrays. 

1. Reversing a 1D Array

For a 1D array (a simple list-like structure), reversing is straightforward and can be done using slicing i.e slicing technique [::-1]



In [13]:
# 1D
import numpy as np

arr_ = np.array([ 1 ,2 , 3 ,4 , 5])

reversed_arr_ = arr_[ : : -1]

print('Original array :' , arr_)
print('Reversed array :' , reversed_arr_)


Original array : [1 2 3 4 5]
Reversed array : [5 4 3 2 1]


2. Reversing a 2D Array

For a 2D array (matrix-like structure), you can reverse elements along different axes: the rows, the columns, or both.You can use slicing with [::-1, :].

In [14]:
#2D
arr_2d = np.array([[2, 4 , 6] , [1 , 3 ,5] ,[8 , 6 , 3]])

reversed_arr_2d = arr_2d[ : : -1 , : ]
print('Original array - ' , arr_2d)
print('reversed array - ' , reversed_arr_2d)

Original array -  [[2 4 6]
 [1 3 5]
 [8 6 3]]
reversed array -  [[8 6 3]
 [1 3 5]
 [2 4 6]]


Q 4. How can you determine the data type of elements in a numpy array discuss the importance of data type in memory management and performance ?

To determine the data type of elements in a NumPy array, you can use the dtype attribute. This tells you the data type (int, float, bool, etc.) of the array elements.

Importance of Data Types in Memory Management and Performance

The choice of data type in NumPy arrays is critical for two main reasons: memory management and performance.

1. Memory Management

Efficient Memory Usage: Different data types use varying amounts of memory. For example:

• int32 uses 4 bytes (32 bits) per element.

• int64 uses 8 bytes (64 bits) per element.

• float32 uses 4 bytes, and float64 uses 8 bytes.                           Choosing a data type that matches your needs can significantly reduce     memory usage, especially when dealing with large arrays.

2. Performance

Faster Computations: Smaller data types generally allow faster computations because they require less processing power and bandwidth to move data in memory.

3. Precision and Accuracy

Trade-off Between Precision and Memory: While smaller data types can save memory and improve performance, they may result in loss of precision for certain calculations.

• Benefits of Data Types :
1.
Memory Efficiency: Reduced memory usage.
2.
Faster Computations: Optimized operations
3..
Improved Accuracy: Reduced error
4.s.
Better Code Readability: Clear data type intentio
• ns.
Best Prac :t
1 .ices
Specify data type during array crea
2.tion.
Use np.dtype to verify data
3. type.
Avoid implicit type conve
4.rsions.
Optimize data type for specific operations.

Q 5. Define and the arrays in numpy and explain their key features how do they differ from Standard Python list?

A NumPy array is a powerful, n-dimensional array object provided by the NumPy library in Python. NumPy arrays are homogeneous, meaning all elements in a NumPy array must be of the same data type, which allows for better performance, memory efficiency, and ease of performing mathematical operations.

### Comparison of NumPy Arrays vs. Python Lists

1.Data Type:

NumPy Array	- Homogeneous  (all elements must be of the same type)

Python List - Heterogeneous (elements can have different types)

2. Memory Efficiency

Numpy array : More memory-efficient, uses contiguous memory.

Python list : Less efficient, elements are pointers to objects in memory.

3. Performance

Numpy array : Faster for numerical operations, especially on large datasets due to vectorization.

Python list : Slower, especially for numerical operations, as you need to iterate through the list manually.

4. Mathematical Operations

Numpy array :Supports element-wise and vectorized operations

Python list : Requires loops for element-wise operations.

5. Fixed Size

Numpy array : Size is fixed once created.

Python list : Size is dynamic (elements can be added or removed).

Q 6. Analyse the performance benefits of numpy Array over the Python list for large scale numerical operations .

### Key Performance Benefits of NumPy Arrays Over Python Lists

1. Memory Efficiency

NumPy arrays are more memory-efficient than Python lists because they store data in contiguous blocks of memory. This allows for more efficient access and manipulation of data.

Python lists, on the other hand, are arrays of pointers to objects, meaning each element is a reference to an object, rather than the object itself. This results in higher memory usage, especially with large datasets.

2. Speed of Numerical Operations

NumPy is optimized for numerical operations by relying on vectorized operations. These operations allow you to perform computations on entire arrays without using loops, which would slow down performance in Python lists.

3.  Lower Overhead in Operations

NumPy operations are compiled at a low level , so they incur less overhead compared to Python's higher-level abstraction in loops and data handling.

In contrast, Python lists rely on high-level abstractions, which are slower, especially when handling large datasets. The operations are interpreted by Python's runtime rather than compiled for performance.

4. . Broadcasting in NumPy

Broadcasting is a powerful feature in NumPy that allows operations to be performed on arrays of different shapes in a memory-efficient manner. NumPy automatically expands smaller arrays to match the shape of larger arrays during operations, eliminating the need for manual looping.

Python lists do not have any concept of broadcasting, and to perform element-wise operations on lists of different sizes, you would need to manually loop and handle the operation.

5. Vectorized Operations in NumPy

Vectorization refers to applying an operation to all elements of a NumPy array without using loops. This is achieved using optimized C or Fortran code under the hood, making operations much faster.

With Python lists, you must loop over the elements manually, which introduces a significant performance bottleneck, especially for large-scale operations.




In [2]:
##numpy broadcasting
import numpy as np
arr = np.arange(6).reshape(2, 3)
scalar = 2

result = arr * scalar
print(result)

[[ 0  2  4]
 [ 6  8 10]]


Q 7. Compare vstack( )  and  hstack( ) function in numpy provide examples demonstrating their usage and output ?

The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively.

1. numpy.vstack()

Purpose: Stacks arrays in sequence vertically (row-wise).

Input: Arrays to be stacked must have the same shape along all but the first axis.

2. numpy.hstack()

Purpose: Stacks arrays in sequence horizontally (column-wise).

Input: Arrays to be stacked must have the same shape along all but the second axis.

In [3]:
#for vstack( )
import numpy as np

#  2D 
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# vertically
vstack_result = np.vstack((array1, array2))

print("Vertical Stack (vstack):")
print(vstack_result)


Vertical Stack (vstack):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
#for hstack( )
import numpy as np

#  2D 
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# vertically
hstack_result = np.hstack((array1, array2))

print("Horizontal Stack (hstack):")
print(hstack_result)


Horizontal Stack (hstack):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q 8. Explain the differences between fliplr ( )  and flipud( )  method in Python including their effects on various array dimension .

The fliplr() and flipud() functions in NumPy are used to flip arrays in the left-right and up-down directions, respectively. Both functions are part of the NumPy library and provide a way to manipulate the orientation of arrays. 

1. numpy.fliplr()

Purpose: Flips an array from left to right (horizontally).

Input: Works on 2D arrays (matrices) and flips each row.

Behavior: For each row, the order of elements is reversed.

2. numpy.flipud()

Purpose: Flips an array from up to down (vertically).

Input: Works on 2D arrays (matrices) and flips each column.

Behavior: For each column, the order of elements is reversed.

### Effects on Various Array Dimensions

1. 1D Arrays:

fliplr(): Not applicable. It will raise a ValueError because it requires a 2D array.

flipud(): Not applicable. It will also raise a ValueError.

2. 2D Arrays:

Both fliplr() and flipud() are applicable 

3. 3D Arrays:

fliplr(): Flips the last axis (width) of each 2D slice along the first axis.

flipud(): Flips along the second axis (height) of each 2D slice along the first axis.

In [7]:
import numpy as np

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])

flipped_lr = np.fliplr(array_2d)

print("Original Array:")
print(array_2d)

print("flipped :"  #flipped horizontally
print(flipped_lr )

Original Array:
[[1 2 3]
 [4 5 6]]
flipped :
[[3 2 1]
 [6 5 4]]


In [9]:
import numpy as np

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])

flipped_lr = np.flipud(array_2d)

print("Original Array:")
print(array_2d)

print("flipped :") #flipped vertically
print(flipped_lr )

Original Array:
[[1 2 3]
 [4 5 6]]
flipped :
[[4 5 6]
 [1 2 3]]


Q 9. Discuss the functionality of the arrays left method in numpy . How does it handle uneven splits?

### Array Split Functionality in NumPy

The array_split() method in NumPy divides an array into multiple sub-arrays along a specified axis.
1. ary: The input array to be split.

2. indices_or_sections: This can be an integer specifying the number of equal-sized sub-arrays to create, or it can be an array of indices at which to split the array.

3. axis: The axis along which to split the array. The default is 0, meaning it will split along the first axis (rows for 2D arrays).

4. Returns: A list of sub-arrays.

5. Handles Uneven Splits: If the array cannot be evenly divided, numpy.array_split() ensures that the extra elements are distributed across the resulting sub-arrays. This is particularly useful when you need to split an array into a specific number of parts, but the total size of the array does not divide evenly.


 ault: 0)
Func
1. tionality
Equal Splits: If indices_or_sections is an integer, the array is divided into equal-sized s
2. ub-arrays.
Uneven Splits: If indices_or_sections is a list of indices, the array is split at those specific points.

In [12]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6])

result = np.array_split(array_1d, 3)

print("Split Result (Even):")
for sub_array in result:
    print(sub_array)

Split Result (Even):
[1 2]
[3 4]
[5 6]


Q 10. Explain the concept of factorization and broadcasting and numpy . how do they contribute to effective array operation ?

1. Factorization in NumPy

Factorization refers to the process of decomposing a complex structure into simpler components. In the context of NumPy, factorization can often relate to operations that involve decomposing arrays, such as linear algebra operations, matrix factorizations .

2. Broadcasting in NumPy

Broadcasting is a powerful feature of NumPy that allows arithmetic operations between arrays of different shapes. It automatically expands the smaller array across the larger array's dimensions without creating copies of the data, making operations more efficient in terms of memory and speed.

### Contribution to effective array operations

1. Efficiency:

Broadcasting eliminates the need for explicit looping and replication of data, making operations faster and less memory-intensive.

2. Numerical Stability:

Factorization techniques can improve numerical stability when solving mathematical problems, such as linear systems.

3. Handling Different Shapes:

Broadcasting allows for flexibility when working with arrays of varying shapes, which is common in real-world data analysis and machine learning applications. 


In [13]:
#broadcasting
import numpy as np

a = np.array([1, 2, 3])

b = np.array([[10], 
              [20], 
              [30]])

result = a + b
print("Result of Broadcasting:")
print(result)

Result of Broadcasting:
[[11 12 13]
 [21 22 23]
 [31 32 33]]


## Practical questions:

Q 1. Create a 3x3 mnumpy array with random integers betwwen 1 and 100 . Then , intercghanges its rows and columns.

In [18]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr_ = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(arr_)

# Transpose the array
arr_transpose = arr_.transpose()
print("\nTransposed array:")
print(arr_transpose)

Original array:
[[37 83 24]
 [27 41 26]
 [56 65 74]]

Transposed array:
[[37 27 56]
 [83 41 65]
 [24 26 74]]


Q 2. Generate a 1D Numpy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 .

In [21]:
import numpy as np

arr_ = np.arange(10)  

arr_2x5 = arr_.reshape(2, 5) 
arr_5x2 = arr_.reshape(5, 2) 

print("1D ARRAY:")
print(arr_)

print("\nReshaped to 2x5 Array:")
print(arr_2x5)

print("\nReshaped to 5x2 Array:")
print(arr_5x2)

1D ARRAY:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q 3.Create a 4x4 numpy array with random float values.Add a border of zeros around it ,resulting in a 6x6 array.

In [22]:
import numpy as np

original_array = np.random.rand(4, 4)

bordered_array = np.pad(original_array, pad_width=1, mode='constant',
                        constant_values=0)

print("Original 4x4 Array:")
print(original_array)

print("\n6x6 Array with Border of Zeros:")
print(bordered_array)

Original 4x4 Array:
[[0.22210399 0.02118719 0.47469599 0.5553811 ]
 [0.05995602 0.18709953 0.51120522 0.1223028 ]
 [0.31455622 0.5226355  0.94025225 0.49397587]
 [0.32653476 0.99444486 0.66477065 0.29864895]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.22210399 0.02118719 0.47469599 0.5553811  0.        ]
 [0.         0.05995602 0.18709953 0.51120522 0.1223028  0.        ]
 [0.         0.31455622 0.5226355  0.94025225 0.49397587 0.        ]
 [0.         0.32653476 0.99444486 0.66477065 0.29864895 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q 4.Using numpy, create an array of integer from 10 to a 60 with a step of 5.

In [23]:
import numpy as np

array = np.arange(10, 61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


Q 5. Create a numpy array of strings .Apply different case transformations (uppercase , lowercase , titlecase etc) to each element.

In [24]:
import numpy as np

string_array = np.array(["hello", "world", "numpy", "array",
                         "transformations"])

uppercase_array = np.char.upper(string_array)        # Uppercase
lowercase_array = np.char.lower(string_array)        # Lowercase
titlecase_array = np.char.title(string_array)        # Titlecase
capitalize_array = np.char.capitalize(string_array)  # Capitalize

# Print the results
print("Original Array:", string_array)
print("Uppercase Array:", uppercase_array)
print("Lowercase Array:", lowercase_array)
print("Titlecase Array:", titlecase_array)
print("Capitalize Array:", capitalize_array)

Original Array: ['hello' 'world' 'numpy' 'array' 'transformations']
Uppercase Array: ['HELLO' 'WORLD' 'NUMPY' 'ARRAY' 'TRANSFORMATIONS']
Lowercase Array: ['hello' 'world' 'numpy' 'array' 'transformations']
Titlecase Array: ['Hello' 'World' 'Numpy' 'Array' 'Transformations']
Capitalize Array: ['Hello' 'World' 'Numpy' 'Array' 'Transformations']


Q 6. Generate a numpy array of words , insert a space between each characterof every word in the array.

In [25]:
import numpy as np

words_array = np.array(["hello", "world", "numpy", "array",
                        "transformations"])

spaced_array = np.char.join(' ', words_array)

print("Original Array:", words_array)
print("Array with spaces:", spaced_array)

Original Array: ['hello' 'world' 'numpy' 'array' 'transformations']
Array with spaces: ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y'
 't r a n s f o r m a t i o n s']


Q 7.create to do the numpy arrays and perform element wise addition subtraction multiplication division.

In [26]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([1, 2, 3, 4, 5])

#  addition
addition_result = array1 + array2

#subtraction
subtraction_result = array1 - array2

# multiplication
multiplication_result = array1 * array2

#  division
division_result = array1 / array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)

Array 1: [10 20 30 40 50]
Array 2: [1 2 3 4 5]
Addition Result: [11 22 33 44 55]
Subtraction Result: [ 9 18 27 36 45]
Multiplication Result: [ 10  40  90 160 250]
Division Result: [10. 10. 10. 10. 10.]


Q 8.use numpy to create a 5 x 5 identity Matrix then extract its diagonal elements.

In [28]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = identity_matrix.diagonal()

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q9.generate a numpy array of 100 random integers between 1 to 1000 .  find and display all prime numbers in this array.

In [29]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

random_array = np.random.randint(1, 1001, size=100)

prime_numbers = [num for num in random_array if is_prime(num)]

print("Random Array:", random_array)
print("Prime Numbers in the Array:", prime_numbers)

Random Array: [990 584 496 967 232 650 130 463 599 876 897 172 233 112 504 335 704  37
 866 725 161  87 930 128 764 196 898  62 287 207 575 560 884 797 183 431
 580 422 420 901 596  92 268 577 880 910  19 144 976 211   1 707  73 771
 142 506 349 219 889  75 399 948 761 581 606 865 489 730 505 726 372 742
 420 372 139 580 980 425 156 629 767 556 766 679 244 368 216 835 681 509
  78 332 545 289 417 716 404 566 416 806]
Prime Numbers in the Array: [967, 463, 599, 233, 37, 797, 431, 577, 19, 211, 73, 349, 761, 139, 509]


Q 10. create a number by array representing daily temperature for a month calculate and display the weekly average.

In [32]:
import numpy as np
import calendar

days_in_month = calendar.monthrange(2024, 1)[1]  
daily_temperatures = np.random.uniform(20, 40, size=days_in_month)  

print("Daily Temperatures (°F):")
print(daily_temperatures)

# Calculate weekly averages
num_weeks = int(np.ceil(days_in_month / 7))  
weekly_averages = [np.mean(daily_temperatures[i*7:(i+1)*7]) 
                   for i in range(num_weeks)]

print("\nWeekly Averages (°F):")
for i, avg in enumerate(weekly_averages):
    print(f"Week {i+1}: {avg:.2f}")


Daily Temperatures (°F):
[22.49377059 32.64732753 38.26775466 25.70553947 31.50081204 31.0875109
 30.10052966 21.85655136 28.66638942 25.02423391 27.98603391 37.58010518
 30.80618729 22.02366288 36.59193214 37.3206421  35.86549178 34.34042435
 35.85518433 35.57873593 36.81065177 20.28057389 33.06669433 37.33927215
 21.92480113 21.18374401 24.40805825 33.78023154 23.03571724 31.30081029
 35.81660279]

Weekly Averages (°F):
Week 1: 30.26
Week 2: 27.71
Week 3: 36.05
Week 4: 27.43
Week 5: 30.05
